### ISSUE TITLE
There is an intent to integrate Prism Studio with MacroDeck

### ISSUE THREAD

**Issue by danilolutz** [naver/prismlivestudio#12]
Hello!

There is an intent to integrate Prism Studio with [MacroDeck](https://www.macrodeck.org/)

**Comment by zengvain** [comment]
A good idea, and any further plans? 
By the way, there is a similar function streamdeck we have supported:
https://github.com/naver/prismlivestudio/tree/master/src/prism/sub/stream-deck

**Comment by danilolutz** [comment]
> A good idea, and any further plans? By the way, there is a similar function streamdeck we have supported: https://github.com/naver/prismlivestudio/tree/master/src/prism/sub/stream-deck

@zengvain 

Nice this stream deck solution! I'll try to help with translation on it! However with this MacroDeck solution, Prism will be more dynamic, more democratic, don't you think?
