### ISSUE TITLE
Incompatible license agreement

### ISSUE THREAD

**Issue by notr1ch** [naver/prismlivestudio#7]
The PRISM Live website and application make reference to a terms of use at https://prismlive.com/en_us/policy/terms_content.html. These terms do not seem compatible with the GPL license agreement of OBS Studio, from which PRISM Live is forked. At the very least, the following issues are obvious:

> The copyright of ‘Application’ (source code of program, executable file and UI/UX, inserted image, other works regarding program) belongs to the ‘Company’, and the ‘User’ has the right of using it with permission under this agreement. 

You cannot claim copyright on the application and source code, as those already belong to the original authors.

> However, the User shall have no rights regarding ‘Application’.

> Article 6 (User Rights and Obligations)
> ①The ‘User’ shall comply with regulations, notices, and related statutes of the ‘Company’ along with regulations under this agreement to use the service of ‘Application’.
> ②The ‘User’ shall not perform the following acts regarding ‘Application’:
> 1. Installation or use of ‘Application’ without Company’s permission.
> 2. Connecting to another person’s internet broadcasting account and airing the show via ‘Application’.
> 3. Reverse-engineering the ‘Application’.
> 4. Providing, distributing, or selling the ‘Application’ at a cost or for free to a third party.
> 5. Defamatory or infringement on rights of a third party by using ‘Application’ (including copyright).
> 6. Violating a related statue including the Information and Communications Network Act by using ‘Application’.
> 7. Making a confusion of provider or operator of ‘Application’.

The user has many rights under the GPL license agreement. You may not impose further restrictions.
```
  6. Each time you redistribute the Program (or any work based on the
Program), the recipient automatically receives a license from the
original licensor to copy, distribute or modify the Program subject to
these terms and conditions.  You may not impose any further
restrictions on the recipients' exercise of the rights granted herein.
You are not responsible for enforcing compliance by third parties to
this License.
```

Please have your team read the license at https://github.com/obsproject/obs-studio/blob/master/COPYING and update the terms as necessary. Thanks.

**Comment by jinkiki** [comment]
We are currently reviewing it internally and will revise it soon.
@notr1ch

**Comment by xxuleman** [comment]
Hello.
Regarding the terms you mentioned, we are in the process of internal revision and will be released on May 13, 2021
And from April 12th to May 13th, a PUSH announcement was published in the app.

The detailed changes are as follows:

Article 6 (User Rights and Obligations)
①The ‘User’ shall comply with regulations, notices, and related statutes of the ‘Company’ along with regulations under this agreement to use the service of ‘Application’.
②The ‘User’ shall not perform the following acts regarding ‘Application’. (Applicable only when using the PRISM mobile app.):
1. Installation or use of ‘Application’ without Company’s permission.
2. Connecting to another person’s internet broadcasting account and airing the show via ‘Application’.
3. Reverse-engineering the ‘Application’.
4. Providing, distributing, or selling the ‘Application’ at a cost or for free to a third party.
5. Defamatory or infringement on rights of a third party by using ‘Application’ (including copyright).
6. Violating a related statue including the Information and Communications Network Act by using ‘Application’.
7. Making a confusion of provider or operator of ‘Application’.

Thanks.

**Comment by notr1ch** [comment]
Thank you for the update!
